export const siteConfig = {
  name: "TRAIC",
  fullName: "TRAIC — Robotics & Innovation Club",
  tagline: "Robotics. Innovation. Engineering.",
  headline: "BUILD BEYOND LIMITS.",
  description:
    "TRAIC is a robotics and innovation community building real-world technology through hardware, software, AI, robotics and experimentation.",
  url: process.env.AUTH_URL || "http://localhost:3000",
  location: {
    name: "University Campus",
    lat: 29.9457,
    lon: 78.1642,
  },
  social: {
    github: "https://github.com/traic-club",
    linkedin: "https://linkedin.com/company/traic",
    instagram: "https://instagram.com/traic.club",
    youtube: "https://youtube.com/@traic",
  },
  contact: {
    email: "contact@traic.dev",
  },
  nav: [
    { label: "About", href: "/about" },
    { label: "Projects", href: "/projects" },
    { label: "Workshops", href: "/workshops" },
    { label: "Events", href: "/events" },
    { label: "Members", href: "/members" },
    { label: "Lab", href: "/lab" },
    { label: "Join", href: "/join" },
  ],
  projectCategories: [
    "ALL",
    "ROBOTICS",
    "AI/ML",
    "IOT",
    "DRONES",
    "WEB",
    "HARDWARE",
    "AUTOMATION",
    "RESEARCH",
  ],
  traicCore: [
    { id: "01", label: "ROBOTICS", key: "robotics" },
    { id: "02", label: "AI / ML", key: "ai-ml" },
    { id: "03", label: "IoT", key: "iot" },
    { id: "04", label: "SOFTWARE", key: "software" },
    { id: "05", label: "AUTOMATION", key: "automation" },
    { id: "06", label: "EMBEDDED SYSTEMS", key: "embedded" },
    { id: "07", label: "DRONES", key: "drones" },
    { id: "08", label: "RESEARCH", key: "research" },
  ],
  ecosystem: {
    root: "ROBOTICS",
    nodes: [
      "Embedded Systems",
      "Computer Vision",
      "AI / ML",
      "IoT",
      "Drones",
      "Automation",
      "Web Development",
      "Mobile",
      "Research",
    ],
  },
  learningPath: [
    "BEGINNER",
    "PROGRAMMING",
    "ELECTRONICS",
    "SENSORS",
    "MICROCONTROLLERS",
    "ROBOTICS",
    "AI",
    "AUTONOMOUS SYSTEMS",
    "INNOVATION",
  ],
  workshopTracks: {
    hardware: ["Arduino", "ESP32", "Sensors", "Motors", "Embedded Systems"],
    software: ["C/C++", "Python", "JavaScript", "React", "Backend Development"],
    ai: ["Machine Learning", "Computer Vision", "NLP", "Generative AI"],
    robotics: ["ROS", "Autonomous Systems", "Robotics Control", "Drones"],
  },
  systemStatus: [
    { label: "CORE SYSTEM", status: "ONLINE" },
    { label: "PROJECT DATABASE", status: "ONLINE" },
    { label: "WORKSHOP ENGINE", status: "ONLINE" },
    { label: "MEMBER NETWORK", status: "ONLINE" },
    { label: "INNOVATION LAB", status: "ACTIVE" },
  ],
} as const;

export type SiteConfig = typeof siteConfig;
